### ISSUE TITLE
Easier Home Assistant Zigbee2MQTT light integration - listen to specific topic and not just state

### ISSUE THREAD

**Issue by htvekov** [sieren/Homepoint#130]
Hi' @sieren

First of all: Great piece of software ! 👍🎉😎

I've had Homepoint in the test pipeline for quite a few months and finally I got time to test with my set up.
My initial struggle was not with Homepoint, but rather my newly bought, but semi defective, M5 stack.
Dead CP210X chip 😖, which took me half a day to realise before I finally programmed the ESP32 directly without further hazzle.

My initial impression of Homepoint - I love it ! 🤗🤗

I searched a lot, but found next to nothing regarding Z2M/MQTT Home Assistant integration - use examples/experiences etc.
So I had to move forward by trial and error 😉

It would really be helpful if users, with similar setup like me, could define a specific JSON payload key for Homepoint to read the light status (`getTopic`)

Example - (for `type: Light` as well):
Define that `jsondata` should be used for `getTopic` and the key to be used in `firstKey`

```JSON
{
      "name": "Bed lamp",
      "setTopic": "zigbee2mqtt/Office bed lamp/set",
      "getTopic": "zigbee2mqtt/Office bed lamp",
      "jsondata": true,
      "firstKey": "state",
      "onValue": "ON",
      "offValue": "OFF"
      }]
```
Then Homepoint could read state directly from HA Z2M integrated lights via standard MQTT messages like this below:

`Zigbee2MQTT:info  2021-01-04 23:57:45: MQTT publish: topic 'zigbee2mqtt/Office bed lamp', payload '{"brightness":251,"color":{"x":0.491,"y":0.39},"linkquality":105,"state":"ON","update":{"state":"idle"},"update_available":false}'`

That would be awesome and much easier without the need for extra automation ! 😎

For now, I use following Home Assistant automation to push all states changes (for a list of MQTT light entities) to Homepoint on topic `zigbee2mqtt/LIGHTS_FRIENDLY_NAME/get` with payload `state`

```YAML
- id: Homepoint push light state via MQTT
  alias: Homepoint push light state via MQTT
  trigger:
    platform: state
    entity_id:
    - light.0x680ae2fffe924460_light # Define your Z2M light entities here
    - light.0x90fd9ffffe838cb3_light # Define your Z2M light entities here
  condition:
    condition: template
    value_template: >
      {{ trigger.to_state.attributes.state !=
          trigger.from_state.attributes.state }}
  action:
  - service: mqtt.publish
    data_template:
      topic: 'zigbee2mqtt/{{trigger.to_state.attributes.friendly_name}}/get'
      payload: "{{ trigger.to_state.attributes.state }}"  
```

Happy New Year ! 🎉🚀

Ciao !

**Comment by sieren** [comment]
Awesome! This is super helpful for me, as some people asked fo Zigbee2MQTT Integration in the past (https://github.com/sieren/Homepoint/issues/71) but sadly my knowledge wasnt sufficient. Your post is a great intro.

One thing though, I suppose `jsondata` should be used consistently for both the Set and Get topics?
At least looking at the Zigbee2MQTT Documentation theres two ways to set a topic, either as json to `zigbee2mqtt/FRIENDLY_NAME/set` or directly to `zigbee2mqtt/[FRIENDLY_NAME]/set/state`.

**Comment by htvekov** [comment]
Hi' @sieren

No worries ! 😎
I'll gladly help and test for you if  needed.
I would also love to see and enjoy using Homepoint with improved Z2M integration 😉

And, as you write, I would also suggest consistant use of JSON messages for Z2M integration as this is the 'standard'.
For most devices you can get/set the `device state` as/with 'raw' payloads. But using JSON messages there's no limitation.
Then it will also be much easier, if you're in future would like to expand and improve further on Homepoint Z2M integration.
You can set/get all allowed device attributes using JSON key/payload. I believe that Z2M is payload upper/lowercase tolerant. Any combination will work AFAIK. 

One final suggestion to this Z2M integration. On startup, Homepoint should cycle through all Z2M devices and sync device status by issuing a get command with an empty payload for the device specified key.

Get specified key payload (well, in fact all payloads are returned):
```JSON
topic: zigbee2mqtt/[FRIENDLY_NAME]/get
payload: {"state": ""}
```

Set specific attribute:
```JSON
topic: zigbee2mqtt/[FRIENDLY_NAME]/set
payload: {"state": "[ATTRIBUTE]"}
```

Ciao ! 🙋‍♂️

**Comment by htvekov** [comment]
Hi' @sieren.

I've mocked up some Home Assistant automations that via MQTT will provide Homepoint integration with Hue lights.

Also made the one HA automation for Z2M light needed, to provide full integration for these as well.
This Z2M automation will be obsolete, when you close this issue 😉😁

Didn't really known where and if you would want such examples on your Homepoint Github page ?
So instead of a PR I've added my setup examples and HA automations below.
If you wish, you're more that welcome to copy and paste from this (I have both Z2M and Hue light entities in my Home Assistant setup 😉)

Wish you a lovely weekend! 🍻😎

**Homepoint example with Z2M & Hue lights:**

Please note that Hue lights are entered with `[entity_id]` in topic NOT `[friendly_name]` !
Hue light `payloads` are in _lower_ case (`'on'` or `'off'`).
Hue light `topics` used: homepointhue/`[entity_id]`/set &
homepointhue/`[entity_id]`/set

```json
{
  "wifi": "my_ssid",
  "password": "my_password",
  "hostname": "Homepoint ILI9341",
  "login": "my_login",
  "webpass": "my_password",
  "mqttbroker": "mqtt://192.168.X.XX",
  "mqttusername": "my_username",
  "mqttpasswd": "my_password",
  "timezone": "CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00",
  "screenSaverMinutes": 10,
  "displayColorInverted": false,
  "ledPinPullup": true,
  "screenRotationAngle": 1,
  "scenes": [{
    "name": "Office",
    "type": "Light",
    "icon": "livingroom",
    "devices": [{
      "name": "Ceiling",
      "setTopic": "homepointhue/light.kontor_loft/set",
      "getTopic": "homepointhue/light.kontor_loft/get",
      "onValue": "on",
      "offValue": "off"
    },
    {
      "name": "Desk",
      "setTopic": "zigbee2mqtt/Office desk lamp/set",
      "getTopic": "zigbee2mqtt/Office desk lamp/get",
      "onValue": "ON",
      "offValue": "OFF"
    },
    {
      "name": "Bed lamp",
      "setTopic": "zigbee2mqtt/Office bed lamp/set",
      "getTopic": "zigbee2mqtt/Office bed lamp/get",
      "onValue": "ON",
      "offValue": "OFF"
    }]
  },
  {
    "name": "Kitchen",
    "type": "Light",
    "icon": "kitchen",
    "devices": [{
      "name": "Kitchen",
      "setTopic": "homepointhue/light.kokken/set",
      "getTopic": "homepointhue/light.kokken/get",
      "onValue": "on",
      "offValue": "off"
    }]  
  },
  {
    "name": "Lux office",
    "type": "Sensor",
    "icon": "door",
    "devices": [{
      "name": "Kontor lux",
      "type": "singleValue",
      "firstIcon":"wattage_small",
      "jsondata": true,
      "firstKey": "illuminance_lux",
      "getTopic": "zigbee2mqtt/Office lux"
    }]
  },
  {
    "name": "Outdoor",
    "type": "Sensor",
    "icon": "door",
    "devices": [{
      "name": "Outdoor",
      "type": "combinedValues",
      "firstIcon": "temperature_small",
      "secondIcon": "humidity_small",
      "jsondata": true,
      "firstKey": "temperature",
      "secondKey": "humidity",
      "getTopic": "zigbee2mqtt/Outdoor"
    }]  
  }]
}
```

First Home Assistant automation is needed to complement Homepoint <--> Z2M integration.

Last two automations handles Homepoint integration with Hue lights.

In both 'publish HA state' automations you need to enter all your light entities/groups that you use in Homepoint
Automations could easily be revised to cope with HA switches and other entity types if needed.


```yaml
# We only need to publish HA state changes to Homepoint, as Homepoint publish changes to Z2M bulbs directly 
- id: Homepoint - Publish HA Z2M light state change to Homepoint via MQTT
  alias: Homepoint - Publish HA Z2M light state change to Homepoint via MQTT
  mode: parallel                      # Use parallel as numerous automations could be running simultanously
  trigger:
    platform: state
    entity_id:
    - light.0x680ae2fffe924460_light  # Enter you Z2M light entities that are exposed in Homepoint
    - light.0x90fd9ffffe838cb3_light  # Homepoint topic for Hue lights is [Friendly_Name] NOT entity_id !
  condition:
    condition: template
    value_template: "{{ trigger.to_state.attributes.state !=\n    trigger.from_state.attributes.state\
      \ }}\n"
  action:
  - service: mqtt.publish
    data_template:
      topic: zigbee2mqtt/{{trigger.to_state.attributes.friendly_name}}/get  # topic: zigbee2mqtt/[entity_id]/get
      payload: '{{ trigger.to_state.attributes.state }}'  # payload is UPPER case ('ON' or 'OFF')

- id: Homepoint - Publish HA Hue lights state change to Homepoint via MQTT
  alias: Homepoint - Publish HA Hue lights state change to Homepoint via MQTT
  mode: parallel        # Use parallel as numerous automations could be running simultanously
  trigger:
    entity_id:
    - light.kontor_loft # Enter you Hue light entities/groups that are used in Homepoint
    - light.kokken     # Homepoint topic for Hue lights is entity_id NOT [Friendly_Name] !
    platform: state
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state !=\n    trigger.from_state.state }}\n"
  action:
  - service: mqtt.publish
    data_template:
      topic: homepointhue/{{trigger.to_state.entity_id}}/get  # topic: homepointhue/[entity_id]/get
      payload: '{{states(trigger.entity_id)}}'  # payload is lower case ('on' or 'off')

- id: Homepoint - Push state change from Homepoint to Hue lights via HA service call
  alias: Homepoint - Push state change from Homepoint to Hue lights via HA service call
  mode: parallel                # Use parallel as numerous automations could be running simultanously
  trigger:
    platform: mqtt
    topic: homepointhue/+/set   # Note: Will trigger on ALL entities used in topic: homepointhue/*/set !!
  action:                       # Turn light on/off depending on payload received
    service_template: "{% if trigger.payload == 'on' %}\n  light.turn_on\n{% else\
      \ %}\n  light.turn_off\n{% endif %}\n"
    data_template:
      entity_id: '{{ trigger.topic.split(''/'')[1] }}'  # Get entity_id from topic

```
